# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Daniel Isangedighi's SDET Portfolio"
#description: >- # this means to ignore newlines until "baseurl:"
description: "Portfolio of Daniel Isangedighi, a Software Development Engineer in Test"
#As a skilled Software Developer in Testing (SDET) with 4+ years of experience, 
#I specialize in developing automated tests, conducting thorough manual tests, and ensuring the delivery of high-quality softwares. 
#My expertise lies in bridging the gap between development and quality assurance to enhance software reliability and performance.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danielisangedighi.github.io" # the base hostname & protocol for your site, e.g. http://example.com

#Social media settings
twitter_username: DanielIsangedighiX
github_username:  danielisangedighi
linkedin_username: daniel-isangedighi-b63644109
email: isangedighidaniel@gmail.com

#Author Information
author:
  name: "Daniel Okworo Isangedighi"
  bio: "Software Development Engineer in Test (SDET)"
  avatar: "/assets/images/passport.jpg"
  location: "Lagos State, Nigeria"
  language: ["Python", "Java", "JavaScript", "Ruby"]

#Navigation links
nav_links:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about"
  - name: "Projects"
    url: "/projects"
  - name: "Blog"
    url: "/blog"
  - name: "Contact"
    url: "/contact"
#  - name: ""
#    url: ""

# Project
projects:
  - name: "GeoLocator"
    description: "This is an MVC Web Application built with Springboot framework to find your locations co-ordinates"
    url: "https://github.com/danielisangedighi/GeoLocator"
# - name: "GeoLocator"
# description: "This is an MVC Web Application built with Springboot framework to find your locations co-ordinates"
#  url: "https://github.com/danielisangedighi/GeoLocator"

#Skills
skills:
  - name: "Java Coding"
    level: "Intermediate"
  - name: "JavaScript Coding"
    level: "Intermediate"
  - name: "GUI Testing"
    level: "Expert"
  - name: "API Testing"
    level: "Intermediate"
  - name: "Selenium"
    level: "Intermediate"
  - name: "Jenkins"
    level: "Intermediate"
  - name: "Docker"
    level: "Intermediate"
#  - name: ""
#    level: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed

# SEO settings
#google_analytics: 

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
